### ISSUE TITLE
Process test cases with validation of result only

### ISSUE THREAD

**Issue by noverium** [noverium/noverium-framework#2]
**Description:**

For now, the framework can process test cases which contain some data to interact with (ex. send over http, or run a remote command) and you can't write a test case which only requires to verify a response from the previous executed test case. The framework should have ability to process test cases which only contains validation details for response from a previous executed test case, for example:

```yml
- test: Run Http request
  id: test1
  url: /get/something
  ...
  
- test: Verify correct response
   from: test1
   validate response:
        validate(json_path(response.some.data)): 123
```

**Required modifications:**

- New type of TestCasePayload and factory in noverium-testdata-reader component which would contain all required information about the test case from a test data file
- New TestCaseProcessor in noverium-core component to be able to process data of the new TestCasePayload
- All TestCasePayload now should support test id field which identifies a test case in a test data file. Id is not mandatory but should be provided if used as a reference in other test case.
