### ISSUE TITLE
Support delete operation of db records

### ISSUE THREAD

**Issue by noverium** [noverium/noverium-framework#3]
**Description:**

At the moment DB test data processor supports only 'find' and 'insert' commands which execute sql `select` or `insert` statements respectively. The framework should support ability to run `delete` sql statement to remove some records in database. 

**Test data example:**

```yml
- test: Clean up db
   db_command: delete
   tables: 
      - table1
      - table2
      - table3

   verify records removed:
       validate(response()): 3
```

```yml
- test: Clean up db
   db_command: delete
   table: table1
   
   where:   # can be any word, ex. columns, expected columns, etc.
       column1: value1
       column2: value2

   verify records removed:
       validate(response()): 1
```

**Required changes:**

- Add new implementation in `noverium-db-jdbc` for `DeleteDao` which would support deletion of records in DB
- The existing DB test data processor should be amended so it would be able to execute `delete` sql statements.
